GPU: [1]
DATA_ROOT: SCUT-EnsText/trainlmdb
PRETRAINED: ''
DIS_LR: 0.00001
DIS_BETA1: 0.0
DIS_BETA2: 0.9
GEN_LR: 0.0001
GEN_BETA1: 0.5
GEN_BETA2: 0.9
BATCH_SIZE: 4
INPUT_SIZE: 512
NUMOFWORKERS: 0
L1_LOSS_WEIGHT: 1
FM_LOSS_WEIGHT: 10
STYLE_LOSS_WEIGHT: 1
CONTENT_LOSS_WEIGHT: 1
INPAINT_ADV_LOSS_WEIGHT: 0.01
NUM_EPOCHES: 500
SAVE_INTERVAL: 10